### ISSUE TITLE
Slider U/I not intuitive 

### ISSUE THREAD

**Issue by StevenGubkin** [kurpau/RR-WebApp#2]
Personally, I would have thought that clicking anywhere would show the next progression.  I see now that clicking on the right progresses and clicking on the left regresses.  I think it would be more intuitive to have arrows to click on.

Thanks for making this by the way!  Great way to share the RR with people quickly and intuitively.

**Comment by kurpau** [comment]
Hi, thanks for your feedback, I'll make sure to implement this.
